apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: gitlab-template-instance
  namespace: default
  annotations:
    template-version: 1.0.2
    tested-operator-version: 4.1.0.23
spec:
  template:
    metadata:
      name: gitlab-template
    parameters:
    - name: APP_NAME
      value: gitlab-test-deploy
    - name: NAMESPACE
      value: default
    - name: STORAGE
      value: 30Gi
    - name: SERVICE_TYPE
      value: LoadBalancer
    - name: SSH_PORT
      value: 2221
