apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: nexus-package-server-instance
  namespace: default
  annotations:
    template-version: 1.1.0
    tested-operator-version: 4.1.0.23
spec:
  template:
    metadata:
      name: nexus-package-server
    parameters:
    - name: DEPLOY_NAME
      value: nexus-private-1
    - name: NAMESPACE
      value: default
    - name: STORAGE
      value: 10Gi

