apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: archiva-package-server-instance
  annotations:
    template-version: 1.1.1
    tested-operator-version: 4.1.0.23
spec:
  template:
    metadata:
      name: archiva-package-server
    parameters:
    - name: DEPLOY_NAME
      value: archiva-private-1
    - name: STORAGE
      value: 10Gi

