apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: cicd-trigger-sample-instance
  annotations:
    template-version: 1.1.1
    tested-operator-version: 4.1.0.23
spec:
  template:
    metadata:
      name: cicd-trigger-template
    parameters:
    - name: APP_NAME
      value: nodejs-sample-app
    - name: SERVICE_ACCOUNT_NAME
      value: tutorial-service

