apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: analyze-image-vulnerabilities
  annotations:
    template-version: 1.0.2
    tested-operator-version: 4.1.0.23
spec:
  params:
  - name: image-url
    default: $(inputs.resources.scanned-image.url)
  resources:
    inputs:
    - name: scanned-image
      type: image
  steps:
  - name: scan-image
    image: tmaxcloudck/klar:v2.4.0
    env:
    - name: CLAIR_ADDR
      value: http://172.22.11.2:30060
    - name: CLAIR_THRESHOLD
      value: '1000'
    - name: REGISTRY_INSECURE
      value: 'TRUE'
    - name: IMAGE_NAME
      value: $(inputs.params.image-url)
    script: |
      #!/bin/sh
      set -x
      /klar $IMAGE_NAME
