apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: mongodb-template-instance
  namespace: default
  annotations:
    template-version: 1.0.2
    tested-operator-version: 4.1.0.23
spec:
  template:
    metadata:
      name: mongodb-template
    parameters:
    - name: APP_NAME
      value: mongodb-sample-app
    - name: NAMESPACE
      description: A Namespace Name
      value: default
    - name: DB_STORAGE
      value: "10Gi"
    - name: SERVICE_TYPE
      value: ClusterIP
    - name: MONGODB_USER
      value: root
    - name: MONGODB_PASSWORD
      value: root
    - name: MONGODB_DATABASE
      value: root
    - name: MONGODB_ADMIN_PASSWORD
      value: root
