apiVersion: tmax.io/v1
kind: Template
metadata:
  name: pypi-package-server
  namespace: default
  annotations:
    template-version: 1.1.0
    tested-operator-version: 4.1.0.23
imageUrl: https://pypi.org/static/images/logo-large.72ad8bf1.svg
provider: tmax
recommend: false
shortDescription: Pypi package server for python pip
longDescription: Pypi package server for python pip
tags:
- pypi
- package-server
- python
- pip
parameters:
- name: DEPLOY_NAME
  displayName: DeploymentName
  description: Deployment name
  required: true
- name: NAMESPACE
  displayName: Namespace
  description: Namespace
  required: true
- name: STORAGE
  displayName: StorageSize
  description: Size of a storage (e.g., 100Mi, 10Gi, ...)
  required: true
plans:
- bindable: false
  description: Pypi package server
  name: pypi-plan0
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${DEPLOY_NAME}-svc
    namespace: ${NAMESPACE}
    labels:
      app: ${DEPLOY_NAME}
  spec:
    selector:
      app: ${DEPLOY_NAME}
    ports:
    - name: http
      port: 8080
      protocol: TCP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${DEPLOY_NAME}-pvc
    namespace: ${NAMESPACE}
    labels:
      app: ${DEPLOY_NAME}
  spec:
    storageClassName: csi-cephfs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${DEPLOY_NAME}
    namespace: ${NAMESPACE}
    labels:
      app: ${DEPLOY_NAME}
  spec:
    selector:
      matchLabels:
        app: ${DEPLOY_NAME}
    template:
      metadata:
        labels:
          app: ${DEPLOY_NAME}
      spec:
        containers:
        - name: pypi
          image: pypiserver/pypiserver:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: pypi-data
            mountPath: /data/packages
        volumes:
        - name: pypi-data
          persistentVolumeClaim:
            claimName: ${DEPLOY_NAME}-pvc

